# Generated by Django 4.1 on 2023-04-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialbook_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
